#!/bin/sh

# Assume it's the Huawei modem if there's a tty.
DEVICE_PATH=/sys/devices/platform/soc/8af8800.usb/8a00000.usb/xhci-hcd.0.auto/usb1/1-1/1-1.3/1-1.3:1.0/ttyUSB*
DEVICE_NAME="$(basename ${DEVICE_PATH})"

# If no modem is plugged in, basename will return "ttyUSB*".
if [ "$DEVICE_NAME" != "ttyUSB*" ]; then
	uci set network.pluggable_modem.device="/dev/${DEVICE_NAME}"
	WWAN_PATH=/sys/devices/platform/soc/8af8800.usb/8a00000.usb/xhci-hcd.0.auto/usb1/1-1/1-1.3/1-1.3:1.2/net/wwan*
	WWAN_NAME="$(basename ${WWAN_PATH})"
	uci set network.pluggable_modem.ifname="${WWAN_NAME}"
	uci commit network
	ifup pluggable_modem
fi
