#!/bin/sh

if [ $# -ne 1 ]; then
	echo "Usage: $0 <interface>"
	exit 1
fi

IFACE="$1"
PROGRAMME=/usr/local/share/tcp-in-udp/tcp_in_udp_tc.o

ip link set "$IFACE" gso_max_segs 0 && \
tc qdisc del dev "$IFACE" clsact 2>/dev/null ; \
tc qdisc replace dev "$IFACE" clsact && \
tc filter add dev "$IFACE" egress handle 2 fw action goto chain 1 && \
tc filter add dev "$IFACE" egress chain 1 bpf object-file "$PROGRAMME" section tc action csum udp && \
tc filter add dev "$IFACE" ingress u32 match ip sport 31001 0xffff action goto chain 1 && \
tc filter add dev "$IFACE" ingress u32 match ip sport 31002 0xffff action goto chain 1 && \
tc filter add dev "$IFACE" ingress u32 match ip sport 31003 0xffff action goto chain 1 && \
tc filter add dev "$IFACE" ingress chain 1 bpf object-file "$PROGRAMME" section tc direct-action
