#!/bin/sh

. /lib/functions.sh

# DHCP Configuration
uci add_list dhcp.lan.dhcp_option='6,1.1.1.1,1.0.0.1'

# Network Configuration
# Set MTU for mob1s1a1, mob1s2a1, mob2s1a1, and mob2s2a1
uci set network.mob1s1a1.mtu='1408'
uci set network.mob1s2a1.mtu='1408'
uci set network.mob2s1a1.mtu='1408'
uci set network.mob2s2a1.mtu='1408'

# Add rule
uci add network rule
uci set network.@rule[-1].priority='0'
uci set network.@rule[-1].lookup='100'
uci set network.@rule[-1].mark='1'

# Add route
uci add network route
uci set network.@route[-1].interface='loopback'
uci set network.@route[-1].type='local'
uci set network.@route[-1].target='0.0.0.0/0'
uci set network.@route[-1].table='100'

# Add pluggable modem
uci set network.pluggable_modem=interface
uci set network.pluggable_modem.apn='internet'
uci set network.pluggable_modem.proto='ncm'
uci set network.pluggable_modem.metric='5'
uci set network.pluggable_modem.auto='0'
uci set network.pluggable_modem.mtu='1408'

# mptcpd Configuration
uci set mptcpd.config.enabled='1'

# sing-box Configuration
uci delete sing-box.main.user
uci set sing-box.main.enabled='1'

# Commit all changes
uci commit dhcp
uci commit network
uci commit mptcpd
uci commit sing-box
